Repository UT-final-project/group1-final-project, pull requests merged in 2021-03, with the labels that each got.

#20 rebuild front end file structure
  .gitignore
  LICENSE
  README.md
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
  my-app/client/src/components/Login/login.js
  my-app/client/src/components/NavHome/nav.js
  my-app/client/src/components/Signup/signup.js
  package.json
  server.js
Labels: front end

#21 added gitignore
  .gitignore
Labels: back end

#24 Concurrent
  package-lock.json
  package.json
  server.js
Labels: back end

#32 Dotenv
  config/passportConfig.js
  initDB.js
  models/User.js
  models/index.js
  models/userTest.js
  package-lock.json
  package.json
  scripts/seedDB.js
  server.js
Labels: back end

#33 Further fleshed out the home page. Now gives a description of the site.
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/components/Home/home.css
  client/src/components/Home/home.js
  client/src/components/Login/login.css
  client/src/components/Login/login.js
  client/src/components/Navbar/navbar.css
  client/src/components/Navbar/navbar.js
  client/src/components/Signup/signup.js
  client/src/components/Signup/singup.css
  client/svg-images/online-resume.svg
Labels: front end

#35 modified mongoose connection for an easier deployment
  client/src/components/Home/home.js
  client/src/components/Login/login.js
  client/src/components/Navbar/navbar.js
  config/passportConfig.js
  initDB.js
Labels: back end

#40 removed dotenv.config
  initDB.js
  server.js
Labels: deployment

#37 added model for resume
  models/Resume.js
  models/index.js
Labels: back end

#41 Updated our landing page with descriptions of what our website consit…
  client/src/components/Home/home.js
Labels: front end

#47 Multiform
  client/src/App.js
  client/src/components/AbstractForm/AbstractForm.js
  client/src/components/CertificateForm/CertificateForm.js
  client/src/components/Confirm/Confirm.js
  client/src/components/EducationForm/EducationForm.js
  client/src/components/Home/home.js
  client/src/components/ProfLinksForm/ProfLinksForm.js
  client/src/components/ProjectsForm/ProjectsForm.js
  client/src/components/SkillsForm/SkillsForm.js
  client/src/components/UserForm/userForm.css
  client/src/components/UserForm/userForm.js
  client/src/components/WorkForm/WorkForm.js
Labels: front end

#53 added a default statement to switch
  client/src/components/UserForm/userForm.js
Labels: front end

#58 Resume controller
  controller/resumeController.js
  routes/api/apiResume.js
  routes/api/index.js
  scripts/seedDB.js
  server.js
Labels: back end

#59 Resume controller
  controller/resumeController.js
  controller/userController.js
  routes/api/apiResume.js
  routes/api/apiUsers.js
Labels: back end

#64 Updated the Resume model to match the UserForm.
  client/src/components/CertificateForm/CertificateForm.js
  client/src/components/Confirm/Confirm.js
  client/src/components/EducationForm/EducationForm.js
  client/src/components/SkillsForm/SkillsForm.js
  client/src/components/UserForm/userForm.css
  client/src/components/WorkForm/WorkForm.js
  client/src/utils/API.js
  models/Resume.js
Labels: back end

#67 Prodbuild
  client/public/manifest.json
  routes/index.js
  server.js
Labels: back end

#70 updated page title - it now says ResuMake
  client/public/index.html
Labels: front end

#71 Trevsbranch
  client/src/components/Login/login.js
  client/src/utils/API.js
  config/isAuthenticated.js
  controller/userController.js
  routes/api/apiUsers.js
Labels: back end

#74 Added text to alert user of error on signup page
  client/src/components/Home/home.css
  client/src/components/Home/home.js
Labels: front end

#83 Adding Logo and Favicon Icons
  client/svg-images/ResumakeLogo.png
  client/svg-images/Rfaviocon.png
Labels: front end

#95 Dynamic forms
  client/src/components/AbstractForm/AbstractForm.js
  client/src/components/CertificateForm/CertificateForm.js
  client/src/components/Confirm/Confirm.css
  client/src/components/Confirm/Confirm.js
  client/src/components/EducationForm/EducationForm.js
  client/src/components/Home/home.js
  client/src/components/Lists/CertificationList/CertificationList.css
  client/src/components/Lists/CertificationList/CertificationList.js
  client/src/components/Lists/EducationList/EducationList.css
  client/src/components/Lists/EducationList/EducationList.js
  client/src/components/Lists/JobList/JobList.css
  client/src/components/Lists/JobList/JobList.js
  client/src/components/Lists/SkillsList/SkillsList.css
  client/src/components/Lists/SkillsList/SkillsList.js
  client/src/components/Login/login.js
  client/src/components/Navbar/navbar.js
  client/src/components/SkillsForm/SkillsForm.js
  client/src/components/UserForm/userForm.js
  client/src/components/WorkForm/WorkForm.js
  client/src/utils/API.js
  models/Resume.js
  package-lock.json
  package.json
Labels: back end, enhancement, front end, help wanted

#102 resolving warnings and errors
  client/src/components/Confirm/Confirm.js
  client/src/components/Login/login.js
  client/src/components/Userhome/userhome.js
Labels: front end

#107 added icons to userhome
  client/src/App.js
  client/src/components/Userhome/userhome.js
Labels: front end

#108 Updated Favicon, user home removed template, updated look
  client/public/index.html
  client/src/components/Navbar/navbar.css
  client/src/components/Navbar/navbar.js
  client/src/components/Userhome/userhome.css
  client/src/components/Userhome/userhome.js
Labels: front end

#110 Resume display
  client/package-lock.json
  client/package.json
  client/src/components/Confirm/Confirm.js
  client/src/components/UserForm/userForm.js
  models/Resume.js
Labels: front end

#112 Deploy
  server.js
Labels: deployment

#120 Updated About page to reflect pictures and styling
  client/src/components/About/about.css
  client/src/components/About/about.js
Labels: front end

#137 Pdf
  client/package-lock.json
  client/src/App.js
  client/src/components/Confirm/Confirm.css
  client/src/components/Confirm/Confirm.js
  client/src/components/Navbar/navbar.js
  client/src/components/NoMatch/NoMatch.js
  client/src/components/PDFContent/PDFContent.js
  client/src/components/UserForm/userForm.js
  client/src/components/Userhome/userhome.js
  client/src/pages/Resume/Resume.css
  client/src/pages/Resume/Resume.js
  client/src/utils/API.js
  controller/resumeController.js
  controller/userController.js
  package-lock.json
  package.json
  routes/api/apiResume.js
  routes/api/apiUsers.js
  routes/index.js
Labels: back end, front end

#142 Exports to PDF
  client/src/pages/Resume/Resume.css
  client/src/pages/Resume/Resume.js
Labels: front end

#143 Pdf
  client/src/App.js
  client/src/components/About/about.js
  client/src/components/Confirm/Confirm.js
  client/src/components/Home/home.js
  client/src/components/Login/login.js
  client/src/components/Navbar/navbar.js
  client/src/components/NothingHere/NothingHere.js
  client/src/components/UserForm/userForm.js
  client/src/components/Userhome/userhome.css
  client/src/components/Userhome/userhome.js
  client/src/utils/UserContext.js
Labels: front end
